#!/usr/bin/env python3
"""Assemble research_out.json from the verified evidence gathered this session."""

import json
from pathlib import Path

WS = Path("/ai-inventor/aii_data/runs/run_UtpduT_D2IS2/3_invention_loop/iter_4/gen_art/gen_art_research_1")

S = [
    (1, "https://raw.githubusercontent.com/dreamfast/abliterlitics/master/README.md",
     "Abliterlitics README (raw, fetched in full)",
     "Four analysis axes; the verbatim parent requirement ('Create a directory with your base model and variants, plus a comparison.json'); comparison.json schema with mandatory 'base'; CLI './abliterlitics.sh auto ./my-comparison/'; 'weights' = 'panel, edit, SVD, correlation, fingerprint, etc.'; src/weight/ = '11 weight analysis scripts'; 234 tests; AGPL-3.0."),
    (2, "https://abliterlitics.dev/", "Abliterlitics project home",
     "Model index: 10 reports (gemma4-e4b ~4.5B/23 variants, gemma4-e2b ~2B/13 techniques, qwen25-7b, qwen3.6-27b, glm-4.7-flash, qwen3.5-27b/9b/4b/2b, qwen3-4b). Confirms four of ten reports are at or below ~4.5B."),
    (3, "https://abliterlitics.dev/models/qwen3.5-9b/", "Qwen3.5-9B Abliteration Comparison (Abliterlitics)",
     "THE load-bearing per-layer report. Tensors changed 42/9.9%, 68/16.0%, 62/14.6%; layers modified 23/32, 29/32, 31/32; 'Layers 0 through 8 have no real edits'; relative edit 2.83/4.89/2.72%; tensor types 3/5/3; top-3 layers with magnitudes; median cosine 1.0, global mean 0.997, '100% of principal angles exceed 0.9 cosine similarity', 42 overlapping, strict subset, corr +0.269; Heretic-HauhauCS 33 tensors/0.136/-0.243; HauhauCS-Huihui 43/0.101/-0.907. Every planner-supplied number re-verified exactly. 'Last updated: August 1, 2026'."),
    (4, "https://abliterlitics.dev/models/qwen3-4b/", "Qwen3-4B-Instruct-2507 Abliteration Comparison (Abliterlitics)",
     "SUB-4.2B report on OUR OWN PANEL FAMILY (36 layers). Heretic 57 tensors/33-36 layers/2.49%; HauhauCS ~50 real of 253/~28-36/~2.5%; Huihui 108/36-36/2.13%. 'All three techniques concentrate changes in layers 12 through 19. Layer 16 is the number one most modified layer across all three techniques.' HauhauCS-Heretic median cosine 0.966, regression slope 1.06. 253 = PEFT LoRA 7x36+1 with most adapters near-zero."),
    (5, "https://abliterlitics.dev/models/qwen3.5-4b/", "Qwen3.5-4B Abliteration Comparison (Abliterlitics)",
     "Second sub-4.2B report (32 layers hybrid). 29/83/120 tensors; 29/32, 28/32, 32/32 layers; 2.52/1.10/9.97% relative edit; top layers L19(0.447)/L23(0.324)/L27(2.907). Heretic-Huihui median cosine 0.00017 (essentially orthogonal) with Heretic still a proper subset - the counterexample that defuses the 0.997 alignment caveat. 27 norm artefacts excluded."),
    (6, "https://abliterlitics.dev/models/gemma4-e2b/", "Gemma4-E2B: 13 Techniques Compared (Abliterlitics)",
     "~2B, 35 layers, 13 independent variants on one base with an explicit E/M/L band table (early 0-10 / mid 11-22 / late 23-34). Layer coverage ranges 7/35 to 35/35. Three tiers: surgical (<=3%, 1 type, 'a narrow band of mid-to-late layers, L16 to L32'), moderate (69-86% coverage), aggressive. '10 of 13 variants are perfect rank-1', eff rank 1.00, top-1 energy 94.9-99.9%. Alignment clusters; 'many technique pairs are nearly orthogonal at cosine around 0.01'."),
    (7, "https://raw.githubusercontent.com/dreamfast/abliterlitics/master/docs/METHODOLOGY.md", "Abliterlitics METHODOLOGY.md",
     "Definitions for every weight metric. Sec 1.1 'Load corresponding tensors from base and variant' + diff=(variant-base).abs().mean(); 1.2 svd(delta_matrix), effective rank, energy; 1.3 QR/Grassmann/overlap; 1.4 fingerprint incl. 'Counter by layer index, revealing depth preferences'; 1.5 cosine; 1.7 stacking D_a/D_b/D_r. Sec 5.2 method-signature table with layer-distribution column: rank-1 'Mid-to-late focused (42-44% late)' vs LEACE 'Uniform (33/33/33%)'. Sec 5.4 GLM-4.7 case study E/M/L percentages 0/46/53, 33/35/33, 32/34/34."),
    (8, "https://raw.githubusercontent.com/p-e-w/heretic/master/src/heretic/model.py", "Heretic model.py (Model.abliterate) + README 'How Heretic works'",
     "THE kernel formula, from source: distance=abs(layer_index-max_weight_position); 'if distance > min_weight_distance: continue'; weight = max_weight + (distance/min_weight_distance)*(min_weight-max_weight). TRIANGULAR with compact support, NOT Gaussian. direction_index float via math.modf + lerp + F.normalize. README: per-component parameters, 'Non-constant ablation weights were previously explored by Maxime Labonne in gemma-3-12b-it-abliterated-v2'."),
    (9, "https://raw.githubusercontent.com/p-e-w/heretic/master/src/heretic/main.py", "Heretic main.py Optuna search bounds",
     "Verbatim: direction_index in [0.4L,0.9L]; max_weight_lower_bound=-0.25 for mlp.down_proj else 0.8, upper 1.5, clamped max(0.0,...); max_weight_position in [0.6L,1.0L]; min_weight as a FRACTION in [0,1]; min_weight_distance in [1.0, max(0.6L,1.0)]. Code-level guarantee that the edit peak sits in the last 40% of the stack and that weights above 1 (over-subtraction) are in range."),
    (10, "https://api.github.com/repos/dreamfast/abliterlitics", "GitHub API - dreamfast/abliterlitics",
     "created_at 2026-04-24T23:53:27Z; pushed_at 2026-07-25; updated_at 2026-08-10; license key agpl-3.0 / spdx AGPL-3.0; 21 stars; size 1572."),
    (11, "https://github.com/dreamfast/abliterlitics", "Abliterlitics repo page",
     "32 commits, 21 stars, 2 forks; directory tree (src/, docs/, runners/, docker/, tests/); LICENSE present."),
    (12, "https://raw.githubusercontent.com/elder-plinius/OBLITERATUS/main/README.md", "OBLITERATUS README",
     "Preset table re-verified: basic 1 / advanced 4 / aggressive 8 / surgical 8 / optimized 4 / inverted 8 / nuclear 8 directions. Layer-SELECTIVE by design ('Which layers are safe to modify vs. which are too entangled'; COSMIC layer selection arXiv:2506.00085; steering target_layers=[10..15]). Describes Heretic's kernel as 'Bell-curve layer weighting' - contradicted by Heretic's own source [8]."),
    (13, "https://raw.githubusercontent.com/p-e-w/heretic/master/config.default.toml", "Heretic config.default.toml",
     "row_normalization = 'full' is the DEFAULT ('renormalizes to preserve original row magnitudes') with full_normalization_lora_rank = 3; orthogonalize_direction = true; n_trials 200 / n_startup_trials 60; winsorization_quantile 1.0. Confirms MPOA-style norm preservation is Heretic's shipped default. No max_weight/min_weight keys here (they are Optuna-sampled, see [9])."),
    (14, "https://api.github.com/repos/p-e-w/heretic/releases?per_page=30", "Heretic releases API",
     "NEGATIVE RESULT: no match for MPOA|row.normalization|norm-preserving|#52 across 30 releases. The plan's 'MPOA merged in PR #52' could NOT be confirmed; the shipped default in [13] confirms the feature, not the PR number."),
    (15, "https://huggingface.co/mlabonne/gemma-3-12b-it-abliterated-v2", "mlabonne gemma-3-12b-it-abliterated-v2 model card",
     "NEGATIVE / PARTIAL: the fetch returned HF page chrome; the 'normal distribution with a certain spread and peak layer' sentence was NOT retrieved this session and no numeric spread or peak-layer value was found published anywhere. Reported as UNOBTAINED rather than transcribed."),
    (16, "https://arxiv.org/html/2607.01854v1", "Has This Checkpoint Been Abliterated? (arXiv:2607.01854)",
     "CRITICAL for novelty: E1 = mean over W of sigma_1^2(dW)/sum sigma_i^2(dW) with dW = W_b - W_c, where W is 'o_proj and down_proj weight matrices from each layer in the MID-STACK BAND B ... the rank-1 energy fraction of the edit, BAND-AVERAGED'. The band idea is already published. Also: auditor holds candidate + attested reference; combined z-sum AUROC 0.95 [.90,.98], E1 alone 0.90; AMS Tier-2 0.66, Tier-1 det 0.35; Coslett DOI 10.5281/zenodo.19383019 and the 'direction-agnostic deviation in activation-geometry fingerprint' characterisation."),
    (17, "https://huggingface.co/blog/grimjim/norm-preserving-biprojected-abliteration", "MPOA - Norm-Preserving Biprojected Abliteration (grimjim, 2025-11-06)",
     "Four-step row-norm-preserving update verbatim (normalize r; decompose W into M and W_hat; p = r_hat^T W_hat, W_hat - alpha*r_hat p^T, renormalize rows; recombine W_new = M W_hat_new) guaranteeing ||W_new,i,:|| = ||W_i,:||. PARTIAL COVERAGE quoted: 'we applied a default scale factor of 1.0, intervening on layers [11..41]' of [0..47]. Layer selection heuristic quality = snr x (1-cos_sim); layers 23 and 29 chosen for Gemma3-12B. Hydra-effect ~70% self-repair justification for multi-layer."),
    (18, "https://huggingface.co/blog/grimjim/orthogonal-reflection-bounded-ablation", "ORBA - Orthogonal Reflection Bounded Ablation (grimjim)",
     "H = I - 2uu^T; Hw = w - 2(u^T w)u; geodesic w' = w + (cos theta - 1)(w.u)u with theta = lambda*arccos(h_hat.f_hat); 'At lambda = 1 the refusal component of w is rotated exactly to its orthogonal complement - zeroed without reflection'. Twice-applied modified Gram-Schmidt ('twice is enough'), with the admission it 'breaks isometry'. Author's own negative result: reflection makes 'misdirected sign-flips the characteristic failure mode'; v4 released as directional ablation, v3 as Householder."),
    (19, "https://arxiv.org/abs/2607.03377", "Spectral Signatures of Large Language Models (arXiv:2607.03377)",
     "NEW competitor, parent-free and data-free: PL_Alpha_Hill (Hill estimator over the top n/2 eigenvalues of W^T W) computed layer-wise then aggregated to a model-level signature; scale-invariant; used for lineage, clustering and performance prediction. RULED OUT because its stated prerequisite is the OPPOSITE of edit detection: 'A critical prerequisite ... is its robustness across downstream adaptations ... the impact of post-training on the weight ESD is minimal.' Reads the top of the spectrum. Also does report depth-wise layer-wise perturbation profiles - the honest caveat."),
    (20, "https://arxiv.org/abs/2608.07921", "Spectral Outliers Reveal Dominant Learned Structure in Transformer Attention (arXiv:2608.07921)",
     "NEW competitor, parent-free per-layer spectral: Marchenko-Pastur separation of each projection matrix into random-like bulk and outliers, across 11 pre-trained transformers, ICMLA 2026. RULED OUT - identifies learned structure, not edits; no safety/abliteration; reads OUTLIERS (top of spectrum); its 'band outliers' are row/column bands WITHIN a matrix, not depth bands across the stack."),
    (21, "https://arxiv.org/html/2512.18901v3", "Gabliteration (arXiv:2512.18901v3, Guelmez)",
     "Ridge projection P = R(R^T R + lambda I_k)^-1 R^T (NOT an exact projector unless lambda=0), k in {1,2,3}; W <- W - alpha_l (W P); dynamic layer selection l* = argmax_l S_l with S_l = ||mu_h - mu_n||_2 over 'the candidate set of layers (excluding the first s and last e layers)'; adaptive alpha_l = alpha_base(1+beta[1-|xi_l|]), xi_l = (2l-|L_eff|-1)/(|L_eff|-1), 'maximum scaling to middle layers ... reduced scaling toward boundaries'. KEY QUOTABLE: 'Unlike the uniform layer modification approach in traditional abliteration' - a published statement of our own uniform-vs-selective contrast."),
    (22, "https://arxiv.org/html/2604.08844v1", "Paul (arXiv:2604.08844) - LoRA weight-space alignment drift",
     "C1 re-verified verbatim: cross-method AUC = 0.00 (n_bootstrap = 972, CI [0.00,0.00]); 'AUC 0.00 is not a null result ... perfect discriminative power with inverted labels'. Self-declared confound Sec 5.8.3: 'Language generation collapsed on all steered adapters at all intensities tested ... GPT-4o scored 0/300 steered responses as harmful, confirming the output is incoherent.' No fix evaluated. rho >= 0.956 severity; rho = 0.72 on N=24 (p<0.001). Features are per-layer spectral features of LoRA weight DELTAS."),
    (23, "https://abliterlitics.dev/techniques/", "Abliteration Techniques Compared (Abliterlitics)",
     "Six technique profiles incl. the three absent from our taxonomy. Apostate: 'orthogonal projection with a balanced profile ... spreads edits across almost all layers with moderate intensity per tensor' - a near-uniform counterexample. Abliterix: Heretic + per-model search. AEON: LEACE-style concept erasure. Huihui: 'gently adjusts a bunch of different parts ... by a small amount each' vs Heretic surgical. Ecosystem ranges: tensors changed 3-53%, relative edit 1-6%, KL 0.001-1.10, ASR 85-100%."),
    (24, "https://api.datacite.org/dois/10.5281/zenodo.19383019", "DataCite record - Coslett (2026), Zenodo 10.5281/zenodo.19383019",
     "CLOSES the dependency's largest residual risk. Full author abstract obtained: scars 'ranging from 7.6 to over 2,300 times the instrument's acceptance threshold' in 'tested published checkpoints from multiple toolchains across two model families'. The Neural Network Identity Series shows the instrument is inference-time output geometry (Paper 1 'Inference-Time Physical Unclonable Functions from Architecture-Invariant Output Geometry'; Paper 2 'Logprob Order-Statistic Geometry'), plus a note bounding file-level verification. Issued 2026-04-02; ORCID 0009-0006-5518-1218; CC BY-NC-ND-4.0 + All Rights Reserved + Patent Pending. Zenodo OAI-PMH still 403; wayback 404."),
    (25, "https://huggingface.co/api/models", "HuggingFace Hub API - two-pass census (this session)",
     "13 search terms, 1068 raw hits, 380 name-prefiltered candidates, 192 resolved, 116 at <=4.2B. All param counts from safetensors.total. Confirms 4,022,468,096 for every Qwen3-4B-Instruct-2507 variant; ORBA/orthogonal-reflection-bounded still ZERO sub-4.2B; gabliterated 54; Apostate 1; Abliterix ~1 genuine; AEON/reaper 0 genuine (name collisions). New traps: the ?search=&full=true endpoint carries no safetensors; quantized MLX re-uploads pass a raw param ceiling. huihui-ai NOT gated, contradicting the dependency."),
    (26, "https://huggingface.co/spaces/pliny-the-prompter/obliteratus/raw/main/obliteratus/analysis/spectral_certification.py", "OBLITERATUS spectral_certification.py (source)",
     "C2 re-verified: def certify(self, harmful_activations: torch.Tensor, harmless_activations: torch.Tensor, layer_idx: int = -1); docstring 'computes the covariance of residual activations and applies the BBP phase transition'; tiers GREEN certified_complete / YELLOW distributed_refusal / RED incomplete; Marchenko-Pastur noise floor. Consumes ACTIVATIONS, not weights: parent-free YES, prompt-free NO, forward-pass-free NO."),
    (27, "https://pypi.org/pypi/reverse-abliterate/json", "reverse-abliterate (PyPI JSON)",
     "C3 re-verified: detection = abliteration_metadata.json, LoRA adapter files, '-OBLITERATED' repo-name convention, 'Weight anomalies | Suspicious shard sizes and filenames', missing quantization config, embedded OBLITERATUS commit hashes, forward-hook registration. Hardening = SHA-256 manifests verified 'against a trusted manifest'. No tensor-value statistic anywhere."),
    (28, "https://arxiv.org/abs/2508.00161", "Watch the Weights / WeightWatch (arXiv:2508.00161, Zhong & Raghunathan)",
     "Confirmed parent-requiring: 'the top singular vectors of the weight difference between a fine-tuned model and its base model correspond to newly acquired behaviors', then monitors activation cosine along those directions. Stops up to 100% of backdoor attacks at <1% FPR."),
    (29, "https://arxiv.org/html/2602.15195v3", "Detecting backdoored LoRA adapters from weights alone (arXiv:2602.15195)",
     "Ruled out with reasons: explicit adapter/base separation ('Let F_theta denote the frozen base model and let A denote a LoRA adapter attached to that model'); single selected layer; 20-dim projection-wise descriptor; SUPERVISED calibration on 400 benign + 100 poisoned adapters per backbone, standardized then thresholded. Backbones Llama-3.2-3B, Qwen2.5-3B, Gemma-2-2B - our exact size class."),
    (30, "https://arxiv.org/abs/2508.06309", "Matrix-Driven Identification and Reconstruction of LLM Weight Homology (arXiv:2508.06309)",
     "Ruled out: MDIR detects weight CORRESPONDENCES between models via polar decomposition + Large Deviation Theory and 'compares only a single pair of matrices at a time' - it answers 'are these two models related', not 'was this one edited'. Inference-free, perfect AUC on LeaFBench."),
]

metric_map = [
    {"abliterlitics_metric": "Tensor comparison / edit magnitude",
     "definition_as_stated": "diff = (variant - base).abs().mean().item(); classified by type, by high/medium/low impact (top 10% by edit norm), and by layer index (METHODOLOGY 1.1)",
     "delta_or_own_tensors": "DELTA", "our_nearest_W_metric": "(none)",
     "verdict": "NO_COUNTERPART - parent-requiring by construction"},
    {"abliterlitics_metric": "Relative edit magnitude",
     "definition_as_stated": "'Norm of edit vectors, relative to base tensor norm' (1.4)",
     "delta_or_own_tensors": "DELTA (numerator and denominator both need the base)",
     "our_nearest_W_metric": "(none)", "verdict": "NO_COUNTERPART"},
    {"abliterlitics_metric": "SVD decomposition of the delta",
     "definition_as_stated": "U,S,Vh = torch.linalg.svd(delta_matrix); effective rank = number of singular values above threshold*S[0]; energy = cumulative sum of squared singular values; top-k left/right singular vector comparison (1.2)",
     "delta_or_own_tensors": "DELTA",
     "our_nearest_W_metric": "W06/W07 stable rank, W08/W09 spectral entropy, W10 top-k decay",
     "verdict": "ANALOGOUS-BUT-DISJOINT - same spectral vocabulary, incompatible input (dW vs the checkpoint's own matrices). NOT identical, unlike two features of 2604.08844"},
    {"abliterlitics_metric": "Subspace alignment",
     "definition_as_stated": "principal subspace of each technique's edit vectors via QR decomposition; Grassmann distance; overlap coefficient = fraction of shared principal components (1.3)",
     "delta_or_own_tensors": "DELTA x2 (needs the base AND two variants)",
     "our_nearest_W_metric": "(none)", "verdict": "NO_COUNTERPART"},
    {"abliterlitics_metric": "Technique fingerprinting (incl. layer distribution + edit magnitude profile)",
     "definition_as_stated": "type distribution; 'Layer distribution: Counter by layer index, revealing depth preferences'; edit magnitude profile = norm of edit vectors relative to base tensor norm; directional signature (1.4)",
     "delta_or_own_tensors": "DELTA",
     "our_nearest_W_metric": "the proposed per-band windowed statistic",
     "verdict": "ANALOGOUS-BUT-DISJOINT - THE closest published depth profile, but it is a delta support/magnitude count, not a spectral statistic, and it needs the parent"},
    {"abliterlitics_metric": "Cross-technique correlation",
     "definition_as_stated": "cosine_sim = dot(a,b)/(norm(a)*norm(b)) between two techniques' edit vectors on the same tensor (1.5)",
     "delta_or_own_tensors": "DELTA x2", "our_nearest_W_metric": "(none)", "verdict": "NO_COUNTERPART"},
    {"abliterlitics_metric": "Expert analysis (MoE)",
     "definition_as_stated": "per-expert edit magnitude, expert utilization change, router weight modification, shared vs expert-specific changes (1.6)",
     "delta_or_own_tensors": "DELTA", "our_nearest_W_metric": "(none)", "verdict": "NO_COUNTERPART"},
    {"abliterlitics_metric": "Stacking investigation",
     "definition_as_stated": "D_a = variant_a - base; D_b = variant_b - base; D_r = D_b - D_a; per-tensor R^2 of D_b = slope*D_a + D_r (1.7)",
     "delta_or_own_tensors": "DELTA x2", "our_nearest_W_metric": "(none)", "verdict": "NO_COUNTERPART"},
    {"abliterlitics_metric": "Abliteration method detection (5.2/5.3)",
     "definition_as_stated": "rule cascade on the fingerprints: LEACE if edit density >90% AND relative edit median <0.0001; rank-k if gate_proj+up_proj also modified; Mamba2 if linear_attn.A_log; MoE / shared-expert / norm rules. Signature table gives a LAYER DISTRIBUTION per method: rank-1 'Mid-to-late focused (42-44% late)' vs LEACE 'Uniform (33/33/33%)'",
     "delta_or_own_tensors": "DELTA",
     "our_nearest_W_metric": "(none) - but this is the external naming of our uniform-vs-depth-weighted axis",
     "verdict": "NO_COUNTERPART as a statistic; DIRECTLY SUPPORTIVE as published taxonomy"},
    {"abliterlitics_metric": "(none)",
     "definition_as_stated": "-", "delta_or_own_tensors": "-",
     "our_nearest_W_metric": "W01-W05 pooled-Gram minimum-eigenvector family; W12-W16",
     "verdict": "DISTINCT, NO COUNTERPART - nothing in Abliterlitics is computable from a single checkpoint. THIS IS THE NOVELTY AXIS"},
]

fingerprints = [
    {"model": "Qwen3-4B-Instruct-2507 (OUR PANEL FAMILY)", "base_params": "~4B (4,022,468,096)", "layers": 36,
     "technique": "Heretic (p-e-w heretic-v4)", "n_tensors_changed": 57, "pct_tensors": "14.3%",
     "layers_modified": "33/36", "layer_coverage": 0.92, "relative_edit_magnitude": "2.49%",
     "top_layers": "all three techniques concentrate in L12-19; L16 is the #1 most modified layer for all three",
     "tensor_types": 2, "source": 4},
    {"model": "Qwen3-4B-Instruct-2507", "base_params": "~4B", "layers": 36, "technique": "HauhauCS (Reaper)",
     "n_tensors_changed": "~50 real (253 with GGUF save noise at ~0.000002 norm)", "pct_tensors": "12.6% real / 63.6% any delta",
     "layers_modified": "~28/36 real (36/36 any delta)", "layer_coverage": 0.78, "relative_edit_magnitude": "~2.5% real (0.61% over all 253)",
     "top_layers": "L12-19, peak L16", "tensor_types": "2 real (7+ any delta)",
     "note": "253 = standard PEFT LoRA config over all linear projections, 7*36+1; most adapters near-zero. Heretic-HauhauCS median cosine 0.966, regression slope 1.06", "source": 4},
    {"model": "Qwen3-4B-Instruct-2507", "base_params": "~4B", "layers": 36, "technique": "Huihui",
     "n_tensors_changed": 108, "pct_tensors": "27.1%", "layers_modified": "36/36", "layer_coverage": 1.00,
     "relative_edit_magnitude": "2.13%", "top_layers": "L12-19, peak L16", "tensor_types": 3, "source": 4},
    {"model": "Qwen3.5-4B", "base_params": "~4B", "layers": 32, "technique": "Heretic (coder3101)",
     "n_tensors_changed": 29, "pct_tensors": "6.8%", "layers_modified": "29/32", "layer_coverage": 0.91,
     "relative_edit_magnitude": "2.52%", "top_layers": "L19 (0.447), L23 (0.377), L20 (0.321)", "tensor_types": 3, "source": 5},
    {"model": "Qwen3.5-4B", "base_params": "~4B", "layers": 32, "technique": "HauhauCS",
     "n_tensors_changed": 83, "pct_tensors": "19.5%", "layers_modified": "28/32", "layer_coverage": 0.88,
     "relative_edit_magnitude": "1.10%", "top_layers": "L23 (0.324), L19 (0.322), L15 (0.318)", "tensor_types": 6,
     "note": "skips full-attention layers 3, 7, 27, 31; 21 linear_attn.A_log tensors", "source": 5},
    {"model": "Qwen3.5-4B", "base_params": "~4B", "layers": 32, "technique": "Huihui",
     "n_tensors_changed": 120, "pct_tensors": "28.2%", "layers_modified": "32/32", "layer_coverage": 1.00,
     "relative_edit_magnitude": "9.97%", "top_layers": "L27 (2.907), L23 (2.879), L19 (2.596)", "tensor_types": 7, "source": 5},
    {"model": "Qwen3.5-9B", "base_params": "~9B", "layers": 32, "technique": "Heretic (trohrbaugh v2)",
     "n_tensors_changed": 42, "pct_tensors": "9.9%", "layers_modified": "23/32", "layer_coverage": 0.72,
     "relative_edit_magnitude": "2.83%", "top_layers": "L17 (4.560), L16 (4.508), L19 (4.504)", "tensor_types": 3,
     "note": "'Layers 0 through 8 have no real edits'; modifies 6 of 8 full-attention layers, skipping 3 and 7", "source": 3},
    {"model": "Qwen3.5-9B", "base_params": "~9B", "layers": 32, "technique": "HauhauCS",
     "n_tensors_changed": 68, "pct_tensors": "16.0%", "layers_modified": "29/32", "layer_coverage": 0.91,
     "relative_edit_magnitude": "4.89%", "top_layers": "L25 (12.329), L23 (12.169), L24 (11.955)", "tensor_types": 5,
     "note": "peaks late (22-25 and 31); zero A_log on the 9B (13 on 2B, 21 on 4B, 42 on 27B - non-monotonic)", "source": 3},
    {"model": "Qwen3.5-9B", "base_params": "~9B", "layers": 32, "technique": "Huihui",
     "n_tensors_changed": 62, "pct_tensors": "14.6%", "layers_modified": "31/32", "layer_coverage": 0.97,
     "relative_edit_magnitude": "2.72%", "top_layers": "L10 (5.276), L14 (4.967), L16 (4.964)", "tensor_types": 3, "source": 3},
    {"model": "GLM-4.7-Flash", "base_params": "~59GB MoE", "layers": 48, "technique": "Heretic",
     "n_tensors_changed": "1826/9491", "pct_tensors": "19.2%", "layers_modified": "34/48", "layer_coverage": 0.71,
     "relative_edit_magnitude": "0.022627 median", "layer_distribution_EML": "0% early / 46% mid / 53% late",
     "note": "'The 0% early-layer percentage indicates Heretic's direction_index optimisation skipped early layers entirely'", "source": 7},
    {"model": "GLM-4.7-Flash", "base_params": "~59GB MoE", "layers": 48, "technique": "Hauhau",
     "n_tensors_changed": "9210/9491", "pct_tensors": "97.0%", "layers_modified": "47/48", "layer_coverage": 0.98,
     "relative_edit_magnitude": "0.000000 median (99.98% param edit density)", "layer_distribution_EML": "33% / 35% / 33%",
     "note": "detected as LEACE: 'The uniform 33/33/33 layer distribution is characteristic of a global method that does not concentrate edits at specific depths'; lowest KL 0.009", "source": 7},
    {"model": "GLM-4.7-Flash", "base_params": "~59GB MoE", "layers": 48, "technique": "Huihui",
     "n_tensors_changed": "3151/9703", "pct_tensors": "32.5%", "layers_modified": "48/48", "layer_coverage": 1.00,
     "relative_edit_magnitude": "0.022524 median", "layer_distribution_EML": "32% / 34% / 34%",
     "note": "only variant modifying router.weight (47 tensors)", "source": 7},
]

gemma_e2b = [
    {"variant": "llmfan46", "changed": 7, "total": 600, "pct": "1.2%", "types": 1, "layers": 7, "EML": "0/86/14"},
    {"variant": "coder3101", "changed": 9, "total": 600, "pct": "1.5%", "types": 1, "layers": 9, "EML": "0/67/33"},
    {"variant": "kasper", "changed": 16, "total": 540, "pct": "3.0%", "types": 1, "layers": 16, "EML": "0/38/62"},
    {"variant": "pew", "changed": 16, "total": 600, "pct": "2.7%", "types": 1, "layers": 16, "EML": "0/44/56"},
    {"variant": "duoneural", "changed": 49, "total": 540, "pct": "9.1%", "types": 2, "layers": 29, "EML": "10/41/49"},
    {"variant": "huihui-v1", "changed": 50, "total": 600, "pct": "8.3%", "types": 2, "layers": 25, "EML": "4/48/48"},
    {"variant": "prithiv", "changed": 50, "total": 600, "pct": "8.3%", "types": 2, "layers": 25, "EML": "4/48/48"},
    {"variant": "treadon", "changed": 48, "total": 540, "pct": "8.9%", "types": 2, "layers": 24, "EML": "8/46/46"},
    {"variant": "huihui-v2", "changed": 60, "total": 600, "pct": "10.0%", "types": 2, "layers": 30, "EML": "20/40/40"},
    {"variant": "trevorjs", "changed": 70, "total": 600, "pct": "11.7%", "types": 2, "layers": 35, "EML": "31/34/34"},
    {"variant": "wangzhang", "changed": 72, "total": 540, "pct": "13.3%", "types": 4, "layers": 26, "EML": "6/44/50"},
    {"variant": "wwtcyberlab", "changed": 96, "total": 600, "pct": "16.0%", "types": 4, "layers": 24, "EML": "8/46/46"},
    {"variant": "ether4o4", "changed": 166, "total": 540, "pct": "30.7%", "types": 6, "layers": 35, "EML": "18/41/41"},
]

alignment = [
    {"model": "Qwen3.5-9B", "pair": "Heretic-Huihui", "n_nontrivial_overlap": 42, "median_cosine": 1.0,
     "correlation": 0.269, "subspace": "100% of principal angles exceed 0.9 cosine similarity; global mean 0.997",
     "subset": "Heretic's 42 are a STRICT SUBSET of Huihui's 62", "source": 3},
    {"model": "Qwen3.5-9B", "pair": "Heretic-HauhauCS", "n_nontrivial_overlap": 33, "median_cosine": 0.136,
     "correlation": -0.243, "subspace": "28.6% alignment", "source": 3},
    {"model": "Qwen3.5-9B", "pair": "HauhauCS-Huihui", "n_nontrivial_overlap": 43, "median_cosine": 0.101,
     "correlation": -0.907, "subspace": "0% alignment", "source": 3},
    {"model": "Qwen3.5-4B", "pair": "Heretic-HauhauCS", "n_nontrivial_overlap": 23, "median_cosine": 0.032,
     "correlation": -0.778, "subspace": "mean 0.347, 32% of principal angles above 0.9", "source": 5},
    {"model": "Qwen3.5-4B", "pair": "Heretic-Huihui", "n_nontrivial_overlap": 29, "median_cosine": 0.00017,
     "correlation": -0.374, "subspace": "essentially orthogonal", "subset": "Heretic a proper subset of Huihui",
     "note": "THE COUNTEREXAMPLE that defuses the 0.997 caveat: same technique pair, different base, near-zero cosine", "source": 5},
    {"model": "Qwen3.5-4B", "pair": "HauhauCS-Huihui", "n_nontrivial_overlap": 48, "median_cosine": 0.00019,
     "correlation": -0.205, "source": 5},
    {"model": "Qwen3-4B", "pair": "Heretic-HauhauCS", "n_nontrivial_overlap": "~50", "median_cosine": 0.966,
     "correlation": "regression slope 1.06", "source": 4},
    {"model": "Gemma4-E2B", "pair": "13-way", "median_cosine": "clusters: Huihui >0.85; Heretic 0.67-0.92; independents <0.71",
     "note": "'many technique pairs are nearly orthogonal at cosine around 0.01'; 'No universal abliteration subspace'", "source": 6},
]

recipe_quotes = {
    "heretic": {
        "urls": ["https://github.com/p-e-w/heretic",
                 "https://raw.githubusercontent.com/p-e-w/heretic/master/src/heretic/model.py",
                 "https://raw.githubusercontent.com/p-e-w/heretic/master/src/heretic/main.py",
                 "https://raw.githubusercontent.com/p-e-w/heretic/master/config.default.toml"],
        "readme_kernel_quote": "max_weight, max_weight_position, min_weight, and min_weight_distance: For each component, these parameters describe the shape and position of the ablation weight kernel over the layers.",
        "readme_prior_art_quote": "Non-constant ablation weights were previously explored by Maxime Labonne in gemma-3-12b-it-abliterated-v2.",
        "readme_float_index_quote": "The residual direction index is a float rather than an integer. For non-integral values, the two nearest residual direction vectors are linearly interpolated.",
        "readme_per_component_quote": "Ablation parameters are chosen separately for each component. I have found that MLP interventions tend to be more damaging to the model than attention interventions, so using different ablation weights can squeeze out some extra performance.",
        "kernel_form_FROM_SOURCE": "distance = abs(layer_index - params.max_weight_position); if distance > params.min_weight_distance: continue; weight = params.max_weight + (distance / params.min_weight_distance) * (params.min_weight - params.max_weight)",
        "kernel_shape_CORRECTED": "TRIANGULAR (piecewise-linear tent) with COMPACT SUPPORT and a hard cutoff - NOT Gaussian and NOT a bell curve, contrary to the plan, the dependency artifact, and OBLITERATUS's own comparison table which calls it 'Bell-curve layer weighting'",
        "optuna_bounds_FROM_SOURCE": {
            "direction_index": "[0.4*last_layer_index, 0.9*last_layer_index]",
            "max_weight": "[0.8, 1.5] for attention; [-0.25, 1.5] for mlp.down_proj; clamped max(0.0, .)",
            "max_weight_position": "[0.6*last_layer_index, 1.0*last_layer_index] - STRUCTURALLY forbids centring the edit early",
            "min_weight": "sampled in [0,1] as a FRACTION of max_weight",
            "min_weight_distance": "[1.0, max(0.6*last_layer_index, 1.0)]"},
        "code_comment": "the refusal direction is typically strongest in layers slightly past the midpoint of the layer stack",
        "mpoa_merge_status": "CONFIRMED AS A SHIPPED DEFAULT, NOT AS PR #52. config.default.toml ships row_normalization = 'full' ('like \"pre\", but renormalizes to preserve original row magnitudes') with full_normalization_lora_rank = 3. The releases API returned NO match for MPOA|row.normalization|norm-preserving|#52 - do NOT cite 'PR #52' without re-verification."},
    "mlabonne_v2": {
        "url": "https://huggingface.co/mlabonne/gemma-3-12b-it-abliterated-v2",
        "status": "UNOBTAINED_THIS_SESSION",
        "what_happened": "huggingface.co served page chrome; the grep matched 53 times inside navigation markup only. The 'normal distribution with a certain spread and peak layer' sentence was NOT retrieved and is NOT transcribed here from the dependency artifact.",
        "what_IS_verified": "Heretic's README independently names this model as the prior art for non-constant ablation weights over layers.",
        "paper_sentence_to_use": "the kernel is documented qualitatively as varying with depth; no spread or peak-layer value is published"},
    "mpoa": {
        "url": "https://huggingface.co/blog/grimjim/norm-preserving-biprojected-abliteration",
        "published": "2025-11-06",
        "four_steps_verbatim": "Step 1: r_hat = r/||r||_2. Step 2: for each row i, m_i = ||W_{i,:}||_2, W_hat = M^-1 W. Step 3: p = r_hat^T W_hat in R^{d_in}; W_hat_ablated = W_hat - alpha * r_hat p^T; renormalize each row to unit length, W_hat_new = normalize(W_hat_ablated, dim=1). Step 4: W_new = M W_hat_new.",
        "norm_guarantee_quote": "This ensures that ||W_new,i,:||_2 = ||W_i,:||_2 for all rows i, preserving the learned importance structure while redirecting computation away from the refusal direction.",
        "partial_coverage_quote": "As before, we applied a default scale factor of 1.0, intervening on layers [11..41].",
        "coverage_note": "31 of 48 layers ([0..47]); both ends excluded",
        "layer_selection_quote": "quality = snr x (1 - cos_sim) ... For Gemma3 12B Instruct, with layers numbered [0..47], we picked the measurements from layers 23 and 29 for broad application.",
        "hydra_justification_quote": "when individual layers are ablated, other layers adaptively compensate to restore approximately 70% of the original computation",
        "plan_quote_not_reverified": "The plan's suggested 'applied to layers 10-34 in this model' from grimjim/Nemo-Instruct-2407-MPOA-v4-12B was NOT re-fetched; use the [11..41] quote from the primary blog post instead."},
    "orba": {
        "url": "https://huggingface.co/blog/grimjim/orthogonal-reflection-bounded-ablation",
        "householder_quote": "For a unit vector u, the Householder reflector is: H = I - 2uu^T. Its action on any vector w decomposes cleanly - the component along u is flipped, the orthogonal complement is unchanged: Hw = w - 2(u^T w)u.",
        "geodesic_quote": "The geodesic rotation from u toward -u, parametrized by lambda: w' = w + (cos theta - 1)(w . u)u where theta = lambda * arccos(h_hat . f_hat). At lambda = 1 the refusal component of w is rotated exactly to its orthogonal complement - zeroed without reflection.",
        "gram_schmidt_quote": "u' = u - (u . h_hat)h_hat ... Applying 'twice is enough' for numerical stability, then renormalized: u'' = u' - (u' . h_hat)h_hat, u_hat = u''/||u''||",
        "isometry_admission_quote": "Applying Gram-Schmidt to the refusal direction prior to ablation is correct for preserving capabilities, although it breaks isometry.",
        "author_negative_result_quote": "Householder reflection, while isometric and analytically exact, introduces token and semantic drift that directional ablation does not - reflection amplifies angular error in a way that projection does not, making misdirected sign-flips the characteristic failure mode rather than incomplete zeroing.",
        "releases": "v3 = Householder (for comparison); v4 = directional ablation (the recommended release). Both 12,187,325,040 params - ABOVE our ceiling.",
        "CRITICAL_DISAMBIGUATION": "lambda=1 is the geodesic endpoint = ANNIHILATION ('zeroed without reflection'); the full Householder reflection is the separate v3 release. The two MUST be scored separately: the reflection is the isometry that leaves no null direction, not the lambda=1 case."},
    "obliteratus": {
        "url": "https://github.com/elder-plinius/OBLITERATUS",
        "preset_table_verbatim": {"basic": "1 (diff-in-means), fast baseline", "advanced": "4 (SVD), norm-preserving, bias projection, 2 passes - DEFAULT",
                                  "aggressive": "8 (SVD), whitened SVD, iterative refinement, 3 passes",
                                  "surgical": "8 (SVD), EGA, head surgery, SAE, layer-adaptive, MoE-aware",
                                  "optimized": "4 (SVD), Bayesian auto-tuned, CoT-aware, KL co-optimized",
                                  "inverted": "8 (SVD), semantic refusal inversion (2x reflection)",
                                  "nuclear": "8 (SVD), all techniques + expert transplant + steering"},
        "direction_counts": "1/4/8/8/4/8/8 - the dependency's numbers re-verified exactly",
        "layer_rule": "NO global layer rule is stated. The tool is layer-SELECTIVE: the 'informed' method auto-configures 'Which layers are safe to modify vs. which are too entangled with capabilities'; COSMIC Layer Selection 'Selects layers where harmful/harmless representations have lowest cosine similarity (most separable)' (arXiv:2506.00085, ACL 2025); steering example uses target_layers=[10,11,12,13,14,15].",
        "REVISES_THE_PLAN": "The plan listed OBLITERATUS presets as UNIFORM. They are not. Layer selection is a first-class feature, so the W05 prediction moves from DETECTED to DEGRADED.",
        "heretic_mischaracterisation": "OBLITERATUS's comparison table calls Heretic's kernel 'Bell-curve layer weighting with 7 global parameters via Optuna TPE search'. Heretic's source shows a triangular tent with compact support - see [8]."},
    "gabliteration": {
        "url": "https://arxiv.org/html/2512.18901v3",
        "ridge_projection": "P = R(R^T R + lambda I_k)^-1 R^T, k typically in {1,2,3}; 'not an exact orthogonal projector ... unless lambda = 0 and R has orthonormal columns'",
        "update": "W_attn^(l) <- W_attn^(l) - alpha_l * (W_attn^(l) P); same for W_mlp^(l)",
        "dynamic_layer_selection": "l* = argmax_{l in L} S_l where S_l = ||mu_h^(l) - mu_n^(l)||_2 and 'L is the candidate set of layers (excluding the first s and last e layers)'",
        "adaptive_alpha": "alpha_l = alpha_base(1 + beta[1 - |xi_l|]) if |L_eff| > 1, else alpha_base(1 + beta); xi_l = (2l - |L_eff| - 1)/(|L_eff| - 1) normalises layer position to [-1,1]",
        "alpha_interpretation_quote": "This formulation provides maximum scaling to middle layers (xi_l approx 0), with reduced scaling toward boundaries (|xi_l| approx 1) to preserve input/output representations.",
        "KEY_QUOTABLE": "Unlike the uniform layer modification approach in traditional abliteration, we developed a principled method for identifying optimal layers based on separability metrics. (Sec 2.5) - a PUBLISHED, third-party statement of our own uniform-vs-selective contrast",
        "self_declared_limitations": "The paper itself lists four limitations of S_l: scale-sensitive (biased toward high-norm layers), captures only translational separation and ignores angular structure, no SNR account, and 'no indication of cross-layer directional stability ... cannot distinguish between isolated local effects and refusal directions that persist coherently across multiple consecutive layers' - the last one is an argument FOR a windowed statistic, made by an abliteration author."},
}

prediction_table = [
    {"recipe": "Plain rank-one / Arditi-style (mlabonne v1, Huihui)",
     "uniform_across_layers": "UNIFORM", "weights_unity": "YES (alpha = 1)", "operation": "ANNIHILATE",
     "verbatim_support": "Gabliteration Sec 2.5: 'the uniform layer modification approach in traditional abliteration' [21]; Huihui measured at 31/32, 32/32, 36/36 and 48/48 layers [3,4,5,7]",
     "W05_prediction": "DETECTED", "W05_reason": "every layer carries a shared near-null direction, so the minimum over layers is still extreme",
     "windowed_prediction": "DETECTED", "windowed_reason": "every window contains edited layers"},
    {"recipe": "Heretic (default, v1.2+)",
     "uniform_across_layers": "DEPTH_WEIGHTED + PARTIAL_COVERAGE", "weights_unity": "MIXED, CAN EXCEED 1 (attn [0.8,1.5]; mlp [-0.25,1.5] clamped at 0)",
     "operation": "NORM_PRESERVING_ANNIHILATE (row_normalization='full' is the shipped default)",
     "verbatim_support": "triangular kernel + 'if distance > min_weight_distance: continue' [8]; max_weight_position forced into [0.6L,1.0L] [9]; measured 23/32 with 'Layers 0 through 8 have no real edits' [3]",
     "W05_prediction": "MISSED", "W05_reason": "the unedited early band sets the minimum at its unedited value",
     "windowed_prediction": "DETECTED", "windowed_reason": "provided a window falls inside [max_weight_position +/- min_weight_distance]; since the peak is forced into the last 40% of the stack, a late-stack window is the high-power one"},
    {"recipe": "mlabonne v2",
     "uniform_across_layers": "DEPTH_WEIGHTED", "weights_unity": "<1 away from the peak", "operation": "ANNIHILATE",
     "verbatim_support": "Heretic README names it as the prior art for non-constant ablation weights [8]; the model card's own sentence was UNOBTAINED this session [15]",
     "W05_prediction": "MISSED or DEGRADED", "W05_reason": "DEGRADED if the kernel has full support with small tails; MISSED if truncated. Which one is an empirical question the experiment can answer",
     "windowed_prediction": "DETECTED", "windowed_reason": "at the peak band"},
    {"recipe": "MPOA",
     "uniform_across_layers": "PARTIAL_COVERAGE", "weights_unity": "YES (default scale factor 1.0)",
     "operation": "NORM_PRESERVING_ANNIHILATE (exact row-norm preservation)",
     "verbatim_support": "'we applied a default scale factor of 1.0, intervening on layers [11..41]' of [0..47] [17]; '||W_new,i,:||_2 = ||W_i,:||_2 for all rows i' [17]",
     "W05_prediction": "MISSED", "W05_reason": "layers 0-10 and 42-47 are unedited and set the minimum",
     "windowed_prediction": "DETECTED", "windowed_reason": "a window inside 11-41 sits entirely in the edited region, and the annihilation there is at unity strength"},
    {"recipe": "ORBA - Householder reflection (v3 release)",
     "uniform_across_layers": "PARTIAL_COVERAGE (multi-layer, Hydra-motivated)", "weights_unity": "reflection is a fixed isometry",
     "operation": "REFLECT",
     "verbatim_support": "H = I - 2uu^T; Hw = w - 2(u^T w)u [18]",
     "W05_prediction": "MISSED", "W05_reason": "a reflection is an isometry: it preserves every singular value, creates no null direction anywhere, and leaves the Gram spectrum unchanged",
     "windowed_prediction": "MISSED", "windowed_reason": "same reason - a window cannot recover a direction that was never annihilated",
     "STATUS": "THE SHARPEST FALSIFICATION TARGET. If a windowed statistic fires on Householder-ORBA, the mechanism as stated is wrong. No public sub-4.2B instance exists, so this must be reimplemented in-house."},
    {"recipe": "ORBA - geodesic at lambda = 1 (v4 release)",
     "uniform_across_layers": "PARTIAL_COVERAGE", "weights_unity": "lambda = 1", "operation": "ANNIHILATE",
     "verbatim_support": "'At lambda = 1 the refusal component of w is rotated exactly to its orthogonal complement - zeroed without reflection' [18]",
     "W05_prediction": "MISSED", "W05_reason": "partial layer coverage, as for MPOA",
     "windowed_prediction": "DETECTED", "windowed_reason": "lambda = 1 IS annihilation, so an in-band window sees a genuine null direction",
     "STATUS": "MUST BE SCORED SEPARATELY FROM v3. Conflating the lambda=1 geodesic with the Householder reflection would make the ORBA falsification test vacuous."},
    {"recipe": "Gabliteration",
     "uniform_across_layers": "ADAPTIVE (argmax layer; first s and last e excluded; alpha peaked at mid-stack)",
     "weights_unity": "NO - alpha_l = alpha_base(1 + beta[1 - |xi_l|]), depth-varying",
     "operation": "RIDGE_PARTIAL", "verbatim_support": "[21] Sec 2.3, 2.5, 2.7",
     "W05_prediction": "MISSED", "W05_reason": "twice over: excluded boundary layers, and the ridge term leaves a residual component even where it acts, so no exact null direction is created",
     "windowed_prediction": "DEGRADED", "windowed_reason": "a mid-stack window sees the largest alpha but the ridge regularisation still prevents an exact null - expect a shifted-but-not-extreme statistic",
     "STATUS": "The most AVAILABLE recipe at our scale (54 sub-4.2B instances), so this prediction is the cheapest one to test."},
    {"recipe": "OBLITERATUS (advanced / aggressive / nuclear)",
     "uniform_across_layers": "PARTIAL_COVERAGE / ADAPTIVE (COSMIC selection; 'informed' picks layers)",
     "weights_unity": "multi-pass (2-3), norm-preserving", "operation": "ANNIHILATE, rank-k (k = 1/4/8)",
     "verbatim_support": "preset table and 'Which layers are safe to modify vs. which are too entangled with capabilities' [12]",
     "W05_prediction": "DEGRADED, not DETECTED", "W05_reason": "REVISES THE PLAN, which listed the presets as uniform. Layer selection is a first-class feature, so the minimum sits on an unselected layer",
     "windowed_prediction": "DETECTED", "windowed_reason": "the strongest expected windowed signal of any recipe - rank-k (4 or 8 directions) annihilation over a selected band is the largest local scar"},
    {"recipe": "Apostate (NEW - not in the eight-recipe taxonomy)",
     "uniform_across_layers": "NEAR-UNIFORM", "weights_unity": "moderate, per-tensor", "operation": "ANNIHILATE (orthogonal projection)",
     "verbatim_support": "'orthogonal projection with a balanced profile. It spreads edits across almost all layers with moderate intensity per tensor ... near-zero cosine similarity to Huihui despite targeting the same tensors' [23]",
     "W05_prediction": "DETECTED", "W05_reason": "near-full coverage is what W05 is built to see - and this is a POSITIVE control the plan did not have",
     "windowed_prediction": "DETECTED", "windowed_reason": "coverage is near-complete so every window is in-band"},
    {"recipe": "AEON (NEW - LEACE-style concept erasure)",
     "uniform_across_layers": "UNIFORM", "weights_unity": "near-zero per tensor", "operation": "CONCEPT ERASURE (LEACE)",
     "verbatim_support": "'AEON tries to erase the concept of refusal from the model entirely' [23]; Abliterlitics' LEACE signature is 'Uniform (33/33/33%)' with '~100% edit density with near-zero individual edits' [7]",
     "W05_prediction": "DETECTED (uniform), but MAGNITUDE UNCERTAIN", "W05_reason": "full coverage favours W05, but near-zero per-tensor edit magnitude may put the scar below the detection floor - a genuinely uncertain case worth flagging",
     "windowed_prediction": "DETECTED, same magnitude caveat",
     "STATUS": "NO genuine sub-4.2B instance found - must be reimplemented in-house if tested."},
]

sub4b = [
    {"repo_id": "YanLabs/Qwen3-4B-Instruct-2507-MPOA", "uploader": "YanLabs", "params": 4022468096,
     "createdAt": "2025-12-20T12:40:11.000Z", "gated": False, "recipe": "MPOA"},
    {"repo_id": "heretic-org/Qwen3-4B-Instruct-2507-heretic", "uploader": "heretic-org", "params": 4022468096,
     "createdAt": "2026-02-14T20:01:13.000Z", "gated": False, "recipe": "Heretic"},
    {"repo_id": "p-e-w/Qwen3-4B-Instruct-2507-heretic", "uploader": "p-e-w", "params": 4022468096,
     "createdAt": "2025-11-15T08:12:30.000Z", "gated": False, "recipe": "Heretic"},
    {"repo_id": "p-e-w/Qwen3-4B-Instruct-2507-heretic-v4", "uploader": "p-e-w", "params": 4022468096,
     "createdAt": "2026-02-14T13:46:55.000Z", "gated": False, "recipe": "Heretic - the exact variant Abliterlitics benchmarked [4]"},
    {"repo_id": "0xA50C1A1/Qwen3-4B-Instruct-2507-SOM-MPOA", "uploader": "0xA50C1A1", "params": 4022468096,
     "createdAt": "2026-04-07T17:19:39.000Z", "gated": False, "recipe": "MPOA (SOM)"},
    {"repo_id": "OBLITERATUS/Qwen3-4B-OBLITERATED", "uploader": "OBLITERATUS", "params": 4022468096,
     "createdAt": "2026-03-20T16:49:26.000Z", "gated": False, "recipe": "OBLITERATUS"},
    {"repo_id": "Bismuth233/Qwen3-4B-OBLITERATED", "uploader": "Bismuth233", "params": 4022468096,
     "createdAt": "2026-04-14", "gated": False, "recipe": "OBLITERATUS"},
    {"repo_id": "DreamFast/qwen3-4b-heretic", "uploader": "DreamFast", "params": 4022468096,
     "createdAt": "2026-03-10", "gated": False, "recipe": "Heretic", "note": "19,464 downloads - most-used sub-4.2B Heretic found"},
    {"repo_id": "DreamFast/Qwen3-4B-2507-Instruct-Uncensored-HauhauCS-Aggressive-Safetensor-Benchmark",
     "uploader": "DreamFast", "params": 4022468096, "createdAt": "2026-04-13T20:44:27.000Z", "gated": False,
     "recipe": "HauhauCS/Reaper", "note": "safetensors conversion (via ungguf) of the GGUF-only HauhauCS original; USE THIS ONE"},
    {"repo_id": "huihui-ai/Huihui-Qwen3-4B-Instruct-2507-abliterated", "uploader": "huihui-ai", "params": 4022468096,
     "createdAt": "2025-08-07T12:05:04.000Z", "gated": False, "recipe": "Huihui",
     "note": "NOT GATED - contradicts the dependency artifact's finding that huihui-ai is gated"},
    {"repo_id": "Goekdeniz-Guelmez/Josiefied-Qwen3-4B-Instruct-2507-gabliterated-v2", "uploader": "Goekdeniz-Guelmez",
     "params": 4022468096, "createdAt": "2025-08-09", "gated": False, "recipe": "Gabliteration"},
    {"repo_id": "prithivMLmods/VibeThinker-3B-heretic_decensored", "uploader": "prithivMLmods", "params": 3085938688,
     "createdAt": "2026-06-19T06:14:07.000Z", "gated": False, "recipe": "Heretic"},
    {"repo_id": "heterodoxin/vibethinker-3b-apostate", "uploader": "heterodoxin", "params": 3397103616,
     "createdAt": "2026-06-22", "gated": False, "recipe": "Apostate",
     "note": "THE ONLY genuine sub-4.2B Apostate found in the census"},
    {"repo_id": "0xA50C1A1/Ministral-3-3B-Instruct-2512-abliterix", "uploader": "0xA50C1A1", "params": 3849090048,
     "createdAt": "2026-08-07", "gated": False, "recipe": "Abliterix",
     "note": "the only genuine (non-quantized) sub-4.2B Abliterix found"},
    {"repo_id": "MagicalAlchemist/Qwen3-1.7B-Magic_decensored", "uploader": "MagicalAlchemist", "params": 1720574976,
     "createdAt": "2026-01-22T15:51:18.000Z", "gated": False, "recipe": "unspecified"},
    {"repo_id": "mlabonne/Qwen3-0.6B-abliterated", "uploader": "mlabonne", "params": 596049920,
     "createdAt": "2025-04-29T09:54:23.000Z", "gated": False, "recipe": "mlabonne"},
    {"repo_id": "spikymoth/smollm3-3b-heresy-mpoa-l-r03-d0.0187", "uploader": "spikymoth", "params": 3075098624,
     "createdAt": "2026-02-08", "gated": False, "recipe": "MPOA"},
    {"repo_id": "TheCluster/Qwen3.5-2B-Uncensored-HauhauCS-Aggressive-MLX-bf16", "uploader": "TheCluster",
     "params": 2213241664, "createdAt": "2026-03-17", "gated": False, "recipe": "HauhauCS (bf16 MLX, NOT quantized)"},
    {"repo_id": "DreamFast/Qwen3-VL-4b-Heretic", "uploader": "DreamFast", "params": 4437815808,
     "createdAt": "2026-07-16T03:56:26.000Z", "gated": False, "recipe": "Heretic",
     "EXCLUDE": "4,437,815,808 params EXCEEDS the 4.2B ceiling despite the '4b' name"},
    {"repo_id": "coder3101/Qwen3.5-4B-heretic", "uploader": "coder3101", "params": 4539265536,
     "createdAt": "2026-03-04T14:17:40.000Z", "gated": False, "recipe": "Heretic",
     "EXCLUDE": "4,539,265,536 EXCEEDS the ceiling despite the '4B' name"},
    {"repo_id": "DreamFast/Gemma4-e2b-abliterlitics", "uploader": "DreamFast", "params": 0,
     "createdAt": "2026-05-23T10:21:34.000Z", "gated": False, "recipe": "-",
     "EXCLUDE": "safetensors.total = 0 (no safetensors index) - unusable as a scored checkpoint"},
    {"repo_id": "HauhauCS/Qwen3-4B-2507-Instruct-Uncensored-HauhauCS-Aggressive", "uploader": "HauhauCS", "params": 0,
     "createdAt": "2026-01-25T03:24:10.000Z", "gated": False, "recipe": "HauhauCS/Reaper",
     "EXCLUDE": "GGUF only, safetensors.total = 0 - use the DreamFast safetensors mirror"},
]

corrections = [
    {"n": 1, "what": "Coslett residual risk",
     "old": "'Coslett UNREACHABLE (HTTP 403) = largest residual risk'; adjacency asserted only via the citing paper 2607.01854 Sec 2",
     "new": "Coslett's DataCite record is reachable and carries the full author abstract. The instrument is an inference-time output-geometry / logprob-order-statistic PUF anchored to a claimed identity; scars 'ranging from 7.6 to over 2,300 times the instrument's acceptance threshold' across published checkpoints from multiple toolchains in two model families. ADJACENT, on primary evidence. Residual risk LARGE/SMALL-but-open -> SMALL.",
     "source": "https://api.datacite.org/dois/10.5281/zenodo.19383019 [24]"},
    {"n": 2, "what": "Novelty of the band idea (MOST IMPORTANT)",
     "old": "the per-band / windowed spectral statistic is treated as wholly new",
     "new": "The band idea is NOT ours. arXiv:2607.01854's E1 is already 'band-averaged' over 'each layer in the mid-stack band B'. Claim only the parent-free, sliding, extremum-scored, bottom-of-spectrum variant, and cite E1 at the point where the band is introduced.",
     "source": "https://arxiv.org/html/2607.01854v1 Sec 3 [16]"},
    {"n": 3, "what": "Heretic's kernel shape",
     "old": "'Heretic per-component optimised kernel', described (by the dependency, the plan and OBLITERATUS) as bell-curve / Gaussian",
     "new": "TRIANGULAR (piecewise-linear tent) with COMPACT SUPPORT and a hard cutoff: 'if distance > min_weight_distance: continue', then linear interpolation. Layers outside the support receive NO edit at all - Heretic produces partial coverage by construction.",
     "source": "https://raw.githubusercontent.com/p-e-w/heretic/master/src/heretic/model.py [8]"},
    {"n": 4, "what": "Heretic's depth restriction",
     "old": "(absent from the draft)",
     "new": "Heretic's Optuna search samples max_weight_position in [0.6L, 1.0L] and direction_index in [0.4L, 0.9L] - the edit peak is code-level forbidden from the early stack. This is an a-priori prediction of early-layer under-editing, independently confirmed by Abliterlitics ('Layers 0 through 8 have no real edits'; GLM E/M/L 0/46/53).",
     "source": "https://raw.githubusercontent.com/p-e-w/heretic/master/src/heretic/main.py [9]; https://abliterlitics.dev/models/qwen3.5-9b/ [3]; METHODOLOGY 5.4 [7]"},
    {"n": 5, "what": "OBLITERATUS's layer behaviour",
     "old": "presets treated as uniform all-layer edits, predicted DETECTED by W05",
     "new": "OBLITERATUS is layer-SELECTIVE by design (COSMIC layer selection; the 'informed' method decides 'which layers are safe to modify'). Its W05 prediction moves from DETECTED to DEGRADED, and it becomes the strongest expected WINDOWED signal instead.",
     "source": "https://github.com/elder-plinius/OBLITERATUS [12]"},
    {"n": 6, "what": "ORBA scoring",
     "old": "'ORBA Householder + geodesic lambda=1' treated as one recipe predicted MISSED by both statistics",
     "new": "TWO recipes. lambda = 1 is the geodesic endpoint and the author states it is 'zeroed WITHOUT reflection' - i.e. annihilation, predicted DETECTED by a windowed statistic. The Householder reflection is the separate v3 release and is the isometry that leaves no null direction. Conflating them makes the ORBA falsification test vacuous.",
     "source": "https://huggingface.co/blog/grimjim/orthogonal-reflection-bounded-ablation [18]"},
    {"n": 7, "what": "Heretic's default row normalization",
     "old": "MPOA and Heretic treated as separate recipes; 'MPOA merged in PR #52'",
     "new": "Heretic's shipped config.default.toml sets row_normalization = 'full' ('renormalizes to preserve original row magnitudes') with full_normalization_lora_rank = 3, so a default Heretic edit IS norm-preserving. The PR number could NOT be confirmed - the releases API returns no match for MPOA/row-normalization/#52. Cite the default, not the PR.",
     "source": "config.default.toml [13]; releases API [14]"},
    {"n": 8, "what": "mlabonne v2's Gaussian kernel sentence",
     "old": "quoted as 'weight factors follow a normal distribution with a certain spread and peak layer'",
     "new": "NOT RE-VERIFIED THIS SESSION - the HF page returned chrome only. Say 'the kernel is documented qualitatively as varying with depth; no spread or peak-layer value is published', and support the depth-weighting claim from Heretic's README instead ('Non-constant ablation weights were previously explored by Maxime Labonne in gemma-3-12b-it-abliterated-v2').",
     "source": "[15] negative result; [8] positive substitute"},
    {"n": 9, "what": "huihui-ai gating",
     "old": "'art_sHF0cggp2IvT found huihui-ai gated'",
     "new": "huihui-ai/Huihui-Qwen3-4B-Instruct-2507-abliterated returns gated = False and is fully resolvable (4,022,468,096 params, created 2025-08-07). No repo in the direct verification set was gated. Report the discrepancy rather than either value alone.",
     "source": "HF API [25]"},
    {"n": 10, "what": "Scope of the Abliterlitics external evidence",
     "old": "plan failure mode F2 anticipated 7B+ only, i.e. 'external corroboration at a larger scale'",
     "new": "Four of ten reports are at or below ~4.5B, including a full weight report on Qwen3-4B-Instruct-2507 (our own panel family) and a 13-variant report on Gemma4-E2B (~2B). This is EXTERNAL SUPPORT AT OUR OWN SCALE. Do not downgrade it.",
     "source": "[2,4,5,6]"},
    {"n": 11, "what": "The uniform-vs-depth-weighted axis is externally named",
     "old": "the uniform/depth-weighted contrast presented as our own framing",
     "new": "Two independent published sources name it first. Abliterlitics' method-signature table gives a 'Layer distribution' per method - rank-1 'Mid-to-late focused (42-44% late)' vs LEACE 'Uniform (33/33/33%)'. Gabliteration Sec 2.5 opens 'Unlike the uniform layer modification approach in traditional abliteration'. Cite both; the framing is corroborated, not invented.",
     "source": "METHODOLOGY 5.2 [7]; arXiv:2512.18901v3 Sec 2.5 [21]"},
    {"n": 12, "what": "The cosine caveat must be pre-empted",
     "old": "(absent)",
     "new": "State in the paper, before a reviewer does, that Heretic and Huihui edits are 99.7% aligned in direction on Qwen3.5-9B (median cosine 1.0, 100% of principal angles above 0.9) while differing in coverage (23/32 vs 31/32) and per-layer magnitude - and that the same technique pair is essentially orthogonal (median cosine 0.00017) on Qwen3.5-4B, so the alignment is a property of one base model, not of the pair. See uniformity_external_support.cosine_caveat_paragraph.",
     "source": "[3,5]"},
    {"n": 13, "what": "Taxonomy completeness",
     "old": "eight-recipe taxonomy",
     "new": "Add Apostate (near-uniform orthogonal projection; 1 genuine sub-4.2B instance; a POSITIVE control the panel currently lacks), Abliterix (Heretic + per-model search; 1 genuine sub-4.2B instance) and AEON (LEACE-style concept erasure; NO genuine sub-4.2B instance - reimplement or omit). Ten entries, three of them newly sourced.",
     "source": "[23,25]"},
    {"n": 14, "what": "HF census methodology",
     "old": "implicitly assumed ?search=&full=true carries safetensors",
     "new": "It does NOT. Param counts must be resolved per repo. Additionally, safetensors.total counts QUANTIZED tensors, so MLX/AWQ/bit-quantized re-uploads of much larger models pass a raw 4.2B ceiling (e.g. gemma-4-26B-...-MLX-2bit resolves to 3,810,036,302). Reading safetensors.total is necessary but not sufficient; exclude quantized repos explicitly.",
     "source": "[25]"},
    {"n": 15, "what": "Windowed statistic multiple-comparison exposure",
     "old": "(absent)",
     "new": "A band statistic scored by the extremum over B correlated windows raises the false-positive rate at any fixed per-band threshold. Fix window width and stride before looking at candidates; calibrate the threshold on the extremum statistic over the negative population, not on a single band; and report the number of windows alongside every threshold.",
     "source": "design consequence, not measured here"},
    {"n": 16, "what": "reverse-abliterate's 'weights' claim",
     "old": "'reads NO tensor values'",
     "new": "Accurate, but the tool's own table claims it 'scans metadata, weights, hooks'. Phrase it as: its only weight-level checks are shard size/filename heuristics and optional SHA-256 manifests verified against a trusted prior manifest - no statistic of tensor content anywhere.",
     "source": "[27]"},
]

must_cite = [
    {"key": "abliterlitics", "ref": "Sapwell, N. Abliterlitics: open-source abliteration forensics. github.com/dreamfast/abliterlitics (AGPL-3.0, created 2026-04-24); reports at abliterlitics.dev",
     "why": "The closest community prior art on the same object (model weights). Not citing it reads as ignorance or evasion. Its parent requirement sharpens our claim, and its per-layer coverage numbers are the only external evidence for our mechanism.", "sources": [1, 2, 3, 4, 5, 6, 7, 10, 11, 23]},
    {"key": "arxiv:2607.03377", "ref": "Zhang, Z., Prasad, I. V., Hu, Y., Liu, Z., Luo, H., Ren, P., Yang, Y. Spectral Signatures of Large Language Models. arXiv:2607.03377 (2026)",
     "why": "The closest PARENT-FREE spectral statistic in the literature. A reviewer will find it. It must be cited and ruled out on the record: it reads the top of the spectrum and its stated design goal is robustness to post-training, i.e. invariance to exactly what we detect.", "sources": [19]},
    {"key": "arxiv:2608.07921", "ref": "Dewage, K., Pensky, M., De Silva, S., Bandara, T. H. Spectral Outliers Reveal Dominant Learned Structure in Transformer Attention. ICMLA 2026; arXiv:2608.07921",
     "why": "Closest random-matrix-theory neighbour: parent-free per-layer MP bulk/outlier separation on the model's own attention weights. Ruled out (reads outliers, no edit detection), but the machinery overlaps and the omission would look careless.", "sources": [20]},
    {"key": "arxiv:2508.06309", "ref": "Zhang, R., Goldstein, D. Matrix-Driven Identification and Reconstruction of LLM Weight Homology. arXiv:2508.06309v3 (2026)",
     "why": "SOTA weight-homology detection with p-values, inference-free, pairwise. Rule it out explicitly as answering lineage rather than edit detection.", "sources": [30]},
    {"key": "coslett2026", "ref": "Coslett, A. R. Safety-Alignment Removal as a Model-Identity Failure - Structural Evidence from Published Weight-Level Mutation Checkpoints. Fall Risk AI; Zenodo 10.5281/zenodo.19383019 (issued 2026-04-02)",
     "why": "Now citable with a verified title, date, DOI and abstract rather than as an unreachable item. Cite as ADJACENT with the inference-time output-geometry qualifier.", "sources": [24]},
    {"key": "gabliteration-uniformity", "ref": "Guelmez, G. Gabliteration. arXiv:2512.18901v3, Sec 2.5",
     "why": "Cite AT THE POINT where the uniform-vs-selective contrast is introduced: 'Unlike the uniform layer modification approach in traditional abliteration'. It is a published, third-party statement of our own framing, and its own listed limitation about 'cross-layer directional stability' is an argument for a windowed statistic made by an abliteration author.", "sources": [21]},
    {"key": "heretic-source", "ref": "Weidmann, P. E. Heretic. github.com/p-e-w/heretic (src/heretic/model.py, src/heretic/main.py, config.default.toml)",
     "why": "The relabelling from uploader effect to recipe effect must be argued from the kernel code, not from paraphrase. Cite the file, not just the README, since the README does not give the functional form.", "sources": [8, 9, 13]},
    {"key": "cosmic", "ref": "COSMIC layer selection, arXiv:2506.00085, ACL 2025 (as used by OBLITERATUS)",
     "why": "Newly surfaced via OBLITERATUS's technique table; it is a published layer-selection criterion for abliteration and therefore part of the partial-coverage story. Verify the arXiv id before citing - it was read from OBLITERATUS's README, not fetched.", "sources": [12]},
    {"key": "reaper-provenance", "ref": "Abliterlitics, 'HauhauCS Abliteration: Benchmarks, Plagiarism Analysis, and GGUF Forensics'",
     "why": "Documents that HauhauCS's Reaper is a relicensed fork of Heretic under PolyForm Noncommercial with an Optuna-guided search over known techniques. Relevant because a panel that treats HauhauCS and Heretic as independent recipes is wrong - on Qwen3-4B their real edits match at median cosine 0.966.", "sources": [4, 23]},
]

structured = {
    "abliterlitics_metric_map": metric_map,
    "abliterlitics_parent_requirement": {
        "quote": "Create a directory with your base model and variants, plus a `comparison.json`",
        "schema_quote": '{"name": "qwen35-4b", "base": "Qwen3.5-4B", "variants": {"heretic": {"path": "Qwen3.5-4B-heretic"}, "hauhau": {...}, "huihui": {...}}}',
        "directory_listing_quote": "my-comparison/ |- comparison.json |- Qwen3.5-4B/  # Base model (safetensors) |- Qwen3.5-4B-heretic/ ...",
        "url": "https://raw.githubusercontent.com/dreamfast/abliterlitics/master/README.md",
        "cli_usage": "./abliterlitics.sh auto ./my-comparison/  (also: weights | kl | lm-eval | harmbench | graphs | report | validate)",
        "base_is_mandatory": "'base' is a required top-level key of comparison.json; there is no single-model mode in the command table; './abliterlitics.sh validate' exists to 'Validate comparison.json and model paths'",
        "reinforced_by_methodology": "METHODOLOGY 1.1: 'Load corresponding tensors from base and variant using memory-mapped safetensors' and diff = (variant - base).abs().mean().item()",
        "interpretation_sentence": "The most capable weight-forensics toolkit the abliteration community has built cannot be run at all without the parent checkpoint sitting in the same directory as the candidate - which is precisely the input a Hub auditor screening an unattested upload does not have, so its existence sharpens rather than blunts the parent-free claim."},
    "abliterlitics_provenance": {
        "first_public_date": "2026-04-24",
        "dating_evidence": ["GitHub API created_at = 2026-04-24T23:53:27Z", "pushed_at 2026-07-25T11:33:59Z", "updated_at 2026-08-10T13:09:56Z", "32 commits / 21 stars / 2 forks", "latest report footer: 'Last updated: August 1, 2026'"],
        "date_status": "UPPER BOUND on authorship. Following the OBLITERATUS precedent, squashed bulk uploads make commit history a weak lower bound; 32 commits for a project with 234 tests, three Dockerfiles and 11 weight-analysis scripts is consistent with development preceding first publication.",
        "licence": "AGPL-3.0 (GitHub API license.key = 'agpl-3.0', spdx_id = 'AGPL-3.0'; README footer '## License AGPL-3.0')",
        "licence_implication": "We may cite and quote its published outputs freely; we would not vendor its code into our pipeline.",
        "author": "Nathan Sapwell (nathan.sapwell.net); HF org DreamFast; Discord community",
        "scale": "10 model reports (~2B to 59B MoE), up to 23 variants on a single base"},
    "abliterlitics_cross_technique_fingerprints": fingerprints,
    "abliterlitics_gemma4_e2b_13_variant_band_table": {
        "band_definition": "E/M/L = early layers 0 to 10 / mid layers 11 to 22 / late layers 23 to 34 (35 text layers)",
        "rows": gemma_e2b,
        "tiers_quote": "Surgical at 3% or less with 1 tensor type: llmfan46, coder3101, kasper, pew. These modify only self_attn.o_proj.weight in a narrow band of mid-to-late layers, L16 to L32. ... Moderate at 8 to 10% with 2 tensor types ... expand layer coverage to 69 to 86%. ... Aggressive at 11 to 31% with 2 to 6 tensor types.",
        "rank_quote": "10 of 13 variants are perfect rank-1. ... avg effective rank 1.00, top-1 energy 94.9 to 99.9%. Exceptions: pew (1.81, Heretic ARA), treadon (1.83, rank-2), ether4o4 (2.29, gate components).",
        "why_it_matters": "This is the single richest external per-band table available: 13 independent abliterations of ONE ~2B base, with layer coverage ranging 7/35 to 35/35 and early-band share ranging 0% to 31%. It is the closest thing to a controlled recipe-versus-coverage experiment that exists outside our own panel."},
    "abliterlitics_alignment_table": alignment,
    "uniformity_external_support": {
        "verdict": "SUPPORTS",
        "supportive_reading": "Layer coverage is measurably not uniform, in two independent senses, on bases shared across techniques and measured by a third party with no stake in our hypothesis. ACROSS TECHNIQUES on one base: Qwen3.5-9B Heretic 23/32 (72%), HauhauCS 29/32 (91%), Huihui 31/32 (97%); Qwen3.5-4B 29/32, 28/32, 32/32; GLM-4.7-Flash 34/48 (71%), 47/48 (98%), 48/48 (100%); Gemma4-E2B 7/35 for llmfan46 against 35/35 for trevorjs and ether4o4, a 5x range on one base. WITHIN a technique across the stack: Heretic peaks at L16-19 on the 9B with layers 0-8 untouched; HauhauCS peaks late at L22-25 and 31; Huihui earlier-middle at L10-17; the GLM E/M/L table gives Heretic 0% early / 46% mid / 53% late against the Hauhau variant's 33/35/33. Abliterlitics also NAMES the axis itself: its method-signature table gives rank-1 Heretic-style 'Mid-to-late focused (42-44% late)' versus LEACE 'Uniform (33/33/33%)', and its detection cascade fires LEACE on 'param edit density above 90% AND relative edit median below 0.0001'. Our f* = 1.00 result says a minimum-over-layers statistic is visible only to a fully global edit; an independently produced forensic report therefore places Heretic below full coverage on a shared base - third-party corroboration of exactly the property H1 predicts causes W05 to miss Heretic checkpoints.",
        "cosine_caveat_paragraph": "A reviewer who reads Abliterlitics' Qwen3.5-9B report will find that Heretic's and Huihui's edits have a median per-tensor cosine similarity of 1.0, a global mean of 0.997, and that 100% of principal angles exceed 0.9 cosine similarity, with Heretic's 42 modified tensors a strict subset of Huihui's 62. Read carelessly, that says the two recipes are interchangeable and our recipe-class story collapses. It does not, because the two claims are about different quantities. Cosine similarity is computed between two edit vectors on a tensor both techniques modified; it is silent about the tensors only one of them modifies, and silent about how large each edit is. On the same page and the same model, Heretic touches 23 of 32 layers with layers 0-8 unedited while Huihui touches 31 of 32, and HauhauCS's per-layer peak magnitude is 12.329 against Heretic's 4.560. The recipes agree almost perfectly on WHICH DIRECTION to remove and differ substantially on WHERE IN THE STACK and HOW COMPLETELY they remove it. Coverage and depth profile are precisely the axis a minimum-over-layers statistic keys on, and precisely the axis a cosine between overlapping edits cannot see. The same report makes the point against itself elsewhere: on Qwen3.5-4B the identical Heretic-Huihui pair has a median cosine of 0.00017, essentially orthogonal, while Heretic remains a proper subset of Huihui - so the 0.997 alignment is a property of one base model, not of the technique pair.",
        "scope_mismatch_caveat": "Three limits. (1) Their 'layers modified' is a DELTA SUPPORT COUNT - layers containing at least one tensor whose (variant - base).abs().mean() exceeds a noise floor - while W05 is a minimum over layers of a pooled-Gram eigenvalue on the candidate's OWN matrices. Correlated by construction, not the same statistic; no result of ours is replicated by theirs. (2) Their numbers are parent-derived, so they are evidence that recipes differ in coverage, NOT evidence that a parent-free statistic can see that difference. (3) Scale: four of ten reports are at or below ~4.5B (better than the plan feared), but the richest cross-technique alignment analysis is on the 9B and 27B - say so wherever a claim rests on those.",
        "coverage_nesting_quotable": "Heretic's 42 real tensors are a strict subset of Huihui's 62. Every tensor Heretic modifies, Huihui also modifies. (Qwen3.5-9B; the same nesting recurs on the 4B and 2B)",
        "our_size_class_quotable": "On Qwen3-4B-Instruct-2507 - our own panel's base model - 'All three techniques concentrate changes in layers 12 through 19. Layer 16 is the number one most modified layer across all three techniques.'"},
    "abliterlitics_citation_paragraph": "Abliterlitics is an open-source abliteration-forensics toolkit (AGPL-3.0, first public 2026-04-24) that compares a base model against its abliterated variants along four axes - weight analysis, KL divergence, capability benchmarks and HarmBench safety - and has published reports on ten base models spanning ~2B to 59B. Its weight axis is the closest published relative of ours: it computes SVDs of the edit, subspace alignment via Grassmann distance, per-layer edit-magnitude profiles and technique fingerprints. Every one of those statistics is computed on the delta. The tool requires the user to \"create a directory with your base model and variants, plus a comparison.json\", and base is a mandatory key; there is no single-checkpoint mode. Its measurements are nonetheless external evidence for our mechanism: on a shared Qwen3.5-9B base, Heretic modifies 23 of 32 layers, HauhauCS 29 and Huihui 31, and Heretic's edits leave layers 0-8 untouched. That coverage difference coexists with near-perfect directional agreement between Heretic and Huihui (median cosine 1.0, global mean 0.997, 100% of principal angles above 0.9) - the recipes differ in depth and completeness, not in direction.",
    "recipe_parameter_quotes": recipe_quotes,
    "recipe_uniformity_prediction_table": prediction_table,
    "prediction_divergence_summary": {
        "agree_DETECTED": ["plain rank-one / Huihui", "Apostate", "AEON (with a magnitude caveat)"],
        "agree_MISSED": ["ORBA Householder reflection (v3)"],
        "DISAGREE_this_is_the_payoff": ["Heretic (MISSED -> DETECTED)", "mlabonne v2 (MISSED/DEGRADED -> DETECTED)", "MPOA (MISSED -> DETECTED)", "ORBA geodesic lambda=1 (MISSED -> DETECTED)", "OBLITERATUS (DEGRADED -> DETECTED)", "Gabliteration (MISSED -> DEGRADED)"],
        "falsification": "If a windowed statistic fails to fire on a Heretic or MPOA checkpoint whose edited band is known, the mechanism is wrong. If it fires on Householder-ORBA, the mechanism is wrong in the other direction. Both directions are testable in advance."},
    "sub4b_checkpoint_table": sub4b,
    "hf_census_summary": {
        "method": "two passes over https://huggingface.co/api/models; 13 search terms; params ALWAYS from safetensors.total on the per-repo endpoint",
        "raw_hits": 1068, "name_prefiltered_candidates": 380, "resolved_with_param_count": 192, "at_or_below_4p2B": 116,
        "per_term_genuine_sub4b": {"gabliterated": 54, "OBLITERATED": 11, "MPOA": 6, "heretic": 6,
                                   "abliterix": "16 name-matched, ~1 genuine (15 are MLX quantizations of gemma-4-26B / E2B)",
                                   "AEON": "10 name-matched, 0 genuine (all the unrelated 'Aeonium' family)",
                                   "reaper": "9 name-matched, 0 genuine (all the username 'reaperdoesntknow')",
                                   "apostate": 1, "HauhauCS": 1, "ORBA": 0, "orthogonal-reflection-bounded": 0,
                                   "gabliteration": "0 hits (use the spelling 'gabliterated')"},
        "stated_coverage_limits": ["the ?search=&full=true endpoint carries NO safetensors, so params required per-repo calls",
                                   "a documented name-based size prefilter was applied, so a sub-4.2B checkpoint whose repo name carries no size token was NOT resolved",
                                   "188 of 380 candidates returned no safetensors.total at all",
                                   "safetensors.total counts QUANTIZED tensors: gemma-4-26B-...-MLX-2bit resolves to 3,810,036,302 and gemma-3n-E4B-...-mlx-4Bit to 2,050,125,904, so a raw param ceiling is necessary but NOT sufficient",
                                   "no repo in the direct verification set was gated"],
        "artifacts": ["hf_census.json", "hf_census_pass2.json", "scan_hf.py", "scan_hf2.py"]},
    "recipes_needing_reimplementation": [
        {"recipe": "ORBA (Householder, v3-style)", "reason": "0 sub-4.2B instances across 35 'ORBA' and 7 'orthogonal-reflection-bounded' hits; re-checked this session, dependency confirmed. Painful because ORBA is the SHARPEST falsification target in the prediction table - the experiment cannot test its own strongest prediction without an in-house implementation. H = I - 2uu^T applied to o_proj/down_proj rows over a stated layer range is ~20 lines; reference releases for comparison are grimjim/gemma-3-12b-it-orthogonal-reflection-bounded-ablation-v3-12B (Householder) and -v4-12B (directional), both 12,187,325,040 params."},
        {"recipe": "AEON", "reason": "0 genuine sub-4.2B instances - all 10 name matches are the unrelated 'Aeonium' model family. LEACE-style concept erasure is the cleanest UNIFORM positive control available in principle, so reimplementing it is worth more than its scarcity suggests."},
        {"recipe": "Apostate", "reason": "NOT strictly needed - one genuine instance exists (heterodoxin/vibethinker-3b-apostate, 3,397,103,616) - but n=1 is thin for a recipe whose published profile ('spreads edits across almost all layers with moderate intensity per tensor') makes it a key near-uniform positive control. Consider reimplementing for a second instance."},
        {"recipe": "Abliterix", "reason": "1 genuine instance (0xA50C1A1/Ministral-3-3B-Instruct-2512-abliterix, 3,849,090,048); the other 15 name matches are MLX quantizations of larger models. Same n=1 caveat."}],
    "positioning_corrections": {
        "C1_paul_2604_08844": {
            "verified_numbers": {"cross_method_AUC": 0.00, "n_bootstrap": 972, "CI": "[0.00, 0.00]",
                                 "severity_rho_min": 0.956, "geometry_behaviour_rho": 0.72, "geometry_behaviour_N": 24,
                                 "binary_split": "23 training / 11 test adapters, zero misclassifications"},
            "confound_quote": "H5-asr-steering: Technically passed; substantively invalid. Language generation collapsed on all steered adapters at all intensities tested. Llama-Guard classified degenerate token repetition as 'unsafe,' producing inflated ASR. GPT-4o scored 0/300 steered responses as harmful, confirming the output is incoherent. The steering-to-LoRA injection method is unsuitable for Llama-3.2-3B at the intensities tested.",
            "auc_quote": "A binary classifier trained on DPO-drifted vs. healthy adapters, tested on steering-derived adapters: AUC = 0.00 (n_bootstrap = 972, CI [0.00, 0.00]). ... AUC 0.00 is not a null result. It indicates perfect discriminative power with inverted labels.",
            "no_fix": "No fix is evaluated; Sec 8 lists 'Cross-method features' as future work.",
            "parent_requirement": "features are per-layer spectral features of LoRA weight DELTAS; its most informative feature needs a healthy-adapter centroid",
            "paper_sentence": "Paul (2026) reports that a spectral weight-space drift classifier trained on DPO-manufactured adapters inverts completely on steering-manufactured ones (AUC 0.00, n_bootstrap = 972, CI [0.00, 0.00]), but the paper also declares that its steering arm produced incoherent generation at every intensity - GPT-4o scored 0 of 300 steered responses as harmful - so the precedent for cross-recipe transfer failure is real but confounded, and no fix was evaluated.",
            "url": "https://arxiv.org/html/2604.08844v1"},
        "C2_obliteratus_certification": {
            "signature_verbatim": "def certify(self, harmful_activations: torch.Tensor, harmless_activations: torch.Tensor, layer_idx: int = -1) -> SpectralCertificate",
            "docstring_verbatim": "After abliteration, it computes the covariance of residual activations and applies the BBP phase transition to determine whether any detectable refusal signal survives.",
            "arg_doc_verbatim": "harmful_activations: (n_harmful, hidden_dim) post-abliteration activations on harmful prompts.",
            "tiers": "GREEN certified_complete / YELLOW distributed_refusal / RED incomplete, against a BBP threshold with a Marchenko-Pastur noise floor and an anisotropy correction",
            "properties": {"parent_free": True, "prompt_free": False, "forward_pass_free": False,
                           "screens_unknown_checkpoints": False, "audits_self_performed_edit": True},
            "paper_sentence": "OBLITERATUS ships a spectral certification module, but it certifies a self-performed edit from post-edit activations on harmful and harmless prompts - its certify() takes harmful_activations and harmless_activations and applies a BBP/Marchenko-Pastur threshold per layer - so it is parent-free but neither prompt-free nor forward-pass-free, and it audits an edit the user just made rather than screening an unknown checkpoint. Our novelty claim is therefore stronger, not weaker.",
            "s2_mirror_caveat": "The dependency's verbatim 'Spectral certification RED is common' pitfall quote was NOT re-fetched this session. This artifact re-verified the module's inputs and tier semantics only. Re-verify that sentence before quoting it.",
            "url": "https://huggingface.co/spaces/pliny-the-prompter/obliteratus/raw/main/obliteratus/analysis/spectral_certification.py"},
        "C3_reverse_abliterate": {
            "detection_checks_verbatim": ["abliteration_metadata.json - 'Created by OBLITERATUS during abliteration'",
                                          "LoRA adapter files - adapter_config.json, adapter_model.safetensors",
                                          "Repo name -OBLITERATED - 'Standard abliteration naming convention'",
                                          "Weight anomalies - 'Suspicious shard sizes and filenames'",
                                          "Missing quantization config on quantized models post-abliteration",
                                          "OBLITERATUS commit hashes - 'Embedded git rev-parse HEAD in config files'",
                                          "Forward hook registration - 'Detects PROBE phase monitoring hooks'"],
            "hardening": "SHA-256 weight manifests, generated and verified 'against a trusted manifest'",
            "reads_tensor_values": False,
            "precision_correction": "The tool's own comparison table claims it 'scans metadata, weights, hooks'. That 'weights' claim resolves to shard size/filename heuristics plus optional SHA-256 manifests requiring a trusted prior manifest - not to any statistic of tensor content. Phrase it that way so the quote and the claim cannot be read as contradicting each other.",
            "paper_sentence": "The only shipped parent-free abliteration detector we are aware of, reverse-abliterate, is a filename-and-metadata scanner: it reads abliteration_metadata.json, adapter files, the -OBLITERATED repo-name convention, embedded OBLITERATUS commit hashes, shard sizes and filenames, and forward hooks - it never reads a tensor value, and its only weight-level check (a SHA-256 manifest) requires a trusted prior manifest of the same checkpoint. It is the software instantiation of our 50.5% repo-id string-match baseline, and naming it first is strictly better than letting a reviewer name it.",
            "url": "https://pypi.org/pypi/reverse-abliterate/json"}},
    "windowed_statistic_novelty": {
        "verdict": "NOVEL-NARROW",
        "queries_run": 12,
        "saturation": "The last four consecutive on-lane queries returned nothing new, meeting the dependency artifact's two-consecutive-empty stopping rule. General web search on this lane is heavily polluted by consumer AI-tool SEO and by 'sliding window attention'; the productive route was direct arXiv reads of the mandatory competitor set plus the two new papers those searches surfaced.",
        "competitors_ruled_out": [
            {"work": "arXiv:2607.01854 (Has This Checkpoint Been Abliterated)", "parent_free": False, "per_band": True,
             "reason": "THE SHARPEST PARTIAL COLLISION, and the plan did not know about it. E1 is already 'band-averaged' over 'each layer in the mid-stack band B'; the same band defines its activation gap. But dW = W_b - W_c requires the parent, the band is a single FIXED mid-stack band rather than a sliding window, and it reads the TOP of the spectrum (sigma_1^2 / sum sigma_i^2). No per-band variant beyond B appears in v1."},
            {"work": "arXiv:2508.00161 WeightWatch", "parent_free": False, "per_band": False,
             "reason": "'the top singular vectors of the weight difference between a fine-tuned model and its base model' - parent-requiring, and it then monitors ACTIVATIONS along those directions."},
            {"work": "arXiv:2602.15195 (backdoored LoRAs from weights alone)", "parent_free": False, "per_band": False,
             "reason": "Explicit adapter/base separation ('Let F_theta denote the frozen base model and let A denote a LoRA adapter attached to that model'), a single SELECTED layer, and SUPERVISED calibration on 400 benign + 100 poisoned adapters per backbone."},
            {"work": "arXiv:2604.08844 (Paul)", "parent_free": False, "per_band": False,
             "reason": "Per-layer spectral features of LoRA weight DELTAS; its most informative feature needs a healthy-adapter population."},
            {"work": "arXiv:2607.03377 Spectral Signatures of LLMs", "parent_free": True, "per_band": False,
             "reason": "THE CLOSEST PARENT-FREE SPECTRAL WORK - cite it. Ruled out because (a) its stated design goal is the OPPOSITE of edit detection: 'A critical prerequisite for a spectral signature to serve as a reliable lineage identifier is its robustness across downstream adaptations ... the impact of post-training on the weight ESD is minimal'; (b) PL_Alpha_Hill is a Hill estimator over the TOP n/2 eigenvalues, i.e. the top of the spectrum; (c) layer-wise values are AGGREGATED to a model-level signature, and the tasks are lineage, clustering and performance prediction. HONEST CAVEAT: it does compute depth-wise layer-wise profiles and reports 'layer-wise response to perturbation ... preserving similar depth-wise trends', so a reviewer could argue the machinery is one step from ours - address that head-on rather than hoping it is missed."},
            {"work": "arXiv:2608.07921 Spectral Outliers", "parent_free": True, "per_band": "within-matrix only",
             "reason": "Parent-free per-layer Marchenko-Pastur bulk/outlier separation on the model's own attention weights, across 11 transformers. Ruled out: no edit detection (goal is identifying learned structure; PEFT and pruning are named as future applications), no safety or abliteration, it reads the OUTLIERS (top), and its 'band outliers' are ROW/COLUMN bands WITHIN a matrix, not depth bands across the stack. Closest RMT neighbour - cite it."},
            {"work": "arXiv:2508.06309 MDIR", "parent_free": False, "per_band": False,
             "reason": "'compares only a single pair of matrices at a time' - answers 'are these two models related' (homology/lineage), not 'was this one edited'."},
            {"work": "Abliterlitics per-layer magnitude profile", "parent_free": False, "per_band": True,
             "reason": "Delta-based, and it even bins edits into E/M/L bands. The closest published DEPTH-BAND PROFILE, and the second reason the band framing must be claimed narrowly."},
            {"work": "OBLITERATUS spectral certification", "parent_free": True, "per_band": False,
             "reason": "Per-layer BBP/Marchenko-Pastur, but it consumes ACTIVATIONS and therefore needs prompts and forward passes."},
            {"work": "Coslett (2026)", "parent_free": "n/a", "per_band": False,
             "reason": "Inference-time output-geometry / logprob-order-statistic PUF anchored to a claimed identity; not a weights-only statistic."}],
        "load_bearing_qualifiers": [
            "PARENT-FREE - no base, no sibling, no adapter/base separation. Alone excludes 2607.01854, WeightWatch, 2604.08844, 2602.15195, MDIR and all of Abliterlitics.",
            "CALIBRATION-FREE - no labelled population of healthy checkpoints. Excludes 2602.15195 and 2604.08844's most informative feature.",
            "BOTTOM-OF-SPECTRUM - a shared near-null direction of the pooled Gram of the candidate's own residual-write matrices. Excludes 2607.03377 and 2608.07921, both of which read the top.",
            "SLIDING band scored by the band EXTREMUM - the only qualifier that is a degree rather than a categorical break, because 2607.01854 already averages E1 over a fixed mid-stack band and Abliterlitics already bins edits into E/M/L. Claim the sliding extremum-scored variant, NOT 'the idea of using a band'."],
        "paper_sentence": "To our knowledge no prior work computes a per-band spectral edit-detection statistic from a single checkpoint without a parent, a sibling, an adapter/base separation or a labelled calibration set; the closest parent-free spectral statistics (PL_Alpha_Hill, arXiv:2607.03377; Marchenko-Pastur outlier separation, arXiv:2608.07921) read the top of the spectrum and are explicitly designed to be invariant to post-training, while the closest band-restricted edit statistic (E1, band-averaged over a mid-stack band, arXiv:2607.01854) requires the parent.",
        "do_not_overclaim": "The band idea is NOT ours - arXiv:2607.01854 published it in July 2026. The parent-free, bottom-of-spectrum, sliding-band statistic is.",
        "multiple_window_threshold_warning": "A per-band statistic scored by the extremum over B windows is a maximum of B CORRELATED statistics (overlapping bands, adjacent layers), so at a fixed per-band threshold the false-positive rate rises with the number of effectively independent windows - and neither B nor a naive Bonferroni B is the right multiplier. The executor should (a) fix window width and stride BEFORE looking at any candidate, (b) calibrate the decision threshold on the EXTREMUM statistic over the negative population rather than on a single band, and (c) report the number of windows alongside every threshold. Note the exposure runs opposite to the benefit: the windowed statistic buys sensitivity to partial-coverage recipes at the cost of more chances to fire on an unedited model, and the paper should quantify both sides. Also note that this INHERITS and AMPLIFIES the existing threshold-brittleness problem (S2 cutoff-transfer failure) rather than solving it."},
    "coslett_residual_sentence": "Coslett (2026) detects abliteration as a structural-identity failure using an inference-time, output-geometry instrument - the series it belongs to is built on 'Inference-Time Physical Unclonable Functions from Architecture-Invariant Output Geometry' and 'Logprob Order-Statistic Geometry', anchored to a claimed model identity - and reports scars 'ranging from 7.6 to over 2,300 times the instrument's acceptance threshold' across published checkpoints from multiple toolchains in two model families; it is therefore adjacent rather than colliding, since it is neither prompt-free nor forward-pass-free and computes no weights-only statistic, and what remains unverified is only the body of the paper itself - the record is CC BY-NC-ND with 'All Rights Reserved, Confidential and Proprietary, Patent Pending', so the full text was not obtainable and a weights-only component inside it, while inconsistent with the series' stated instrument, cannot be formally excluded.",
    "coslett_record": {
        "doi": "10.5281/zenodo.19383019",
        "title": "Safety-Alignment Removal as a Model-Identity Failure - Structural Evidence from Published Weight-Level Mutation Checkpoints",
        "creator": "Coslett, Anthony (ORCID 0009-0006-5518-1218), Fall Risk Research",
        "issued": "2026-04-02", "publisher": "Zenodo", "type": "Preprint",
        "rights": "CC BY-NC-ND-4.0 + 'Copyright (C) 2026 Anthony Ray Coslett / Fall Risk AI, LLC. All Rights Reserved.' + 'Confidential and Proprietary. Patent Pending (Applications 63/982,893, 63/990,487, 63/996,680, 64/003,244).'",
        "headline_quote": "in tested published checkpoints from multiple toolchains across two model families, the mutation leaves measurable structural scars ranging from 7.6 to over 2,300 times the instrument's acceptance threshold",
        "instrument_evidence": "Series papers: 1 'The delta-Gene: Inference-Time Physical Unclonable Functions from Architecture-Invariant Output Geometry'; 2 'Template-Based Endpoint Verification via Logprob Order-Statistic Geometry'; plus 'Artifact Identity Is Not Runtime Identity - Trustfall Lite and the Boundary of File-Level Model Verification'",
        "access_routes": {"api.datacite.org": "200 - WORKS, full abstract",
                          "zenodo.org/oai2d GetRecord": "403", "web.archive.org fallrisk.ai": "404"},
        "residual_risk": "SMALL (downgraded from the dependency's SMALL-but-open, because adjacency now rests on the primary record's own abstract and series description rather than on a one-clause characterisation in a citing paper)"},
    "corrections_to_draft": corrections,
    "must_cite_additions": must_cite,
    "confidence": {
        "high": "Abliterlitics metric map, parent requirement, licence, creation date and all numeric fingerprints (Qwen3.5-9B / Qwen3.5-4B / Qwen3-4B / Gemma4-E2B / GLM-4.7); Heretic's kernel code and Optuna bounds; MPOA's four steps and [11..41]; ORBA's Householder and lambda=1 formulation and the author's negative result; OBLITERATUS's preset table and certify() signature; Gabliteration's l*, P and alpha_l; the 2604.08844 numbers; reverse-abliterate's checks; 2607.01854's band-averaged E1; the HF param counts.",
        "medium": "The A4(a) interpretation - the coverage numbers are real, but the inference that a minimum-over-layers statistic must therefore miss Heretic is ours and untested externally; the B2 predictions, reasoned from published formulas rather than measured; the Apostate/Abliterix availability counts, which rest on repo-name search.",
        "low_or_unverified": "The mlabonne v2 'normal distribution ... spread and peak layer' sentence (NOT obtained this session - do not quote as verified); 'MPOA merged in PR #52' (the default config confirms the feature, not the PR); the OBLITERATUS 'Spectral certification RED is common' pitfall sentence (carried from the dependency, not re-fetched); the COSMIC arXiv id 2506.00085 (read from OBLITERATUS's README, not fetched); true parameter counts of quantized repos; everything inside Coslett's body text.",
        "what_would_change_the_verdicts": "A published version of 2607.01854 (or a successor) adding a SLIDING band variant, or any parent-free statistic reading the bottom of the spectrum, would move the novelty verdict from NOVEL-NARROW to SCOOPED. An Abliterlitics report showing a technique with genuinely uniform full-stack coverage AND a Heretic-like KL profile would weaken the uniformity support. Obtaining Coslett's body text and finding a weights-only statistic in it would force the residual sentence to be rewritten."},
}

answer = (WS / "answer_prose.md").read_text()

out = {
    "title": "Last Prior Art and Recipe Evidence",
    "summary": (WS / "summary.txt").read_text().strip(),
    "answer": answer,
    "sources": [{"index": i, "url": u, "title": t, "summary": s} for i, u, t, s in S],
    "structured_answer": structured,
    "follow_up_questions": [
        "Does any later version of arXiv:2607.01854 replace its single fixed mid-stack band B with a swept or sliding band, and does the paper report how E1's AUROC varies with the band's position and width? That single ablation would either confirm the sliding variant as the remaining novelty or collapse it.",
        "Can Abliterlitics' published per-layer edit-magnitude profiles for the Qwen3-4B and Gemma4-E2B reports be obtained as raw numbers (SVG graph data or a results JSON) rather than top-3 summaries, so that the correlation between their delta-support coverage and our parent-free windowed statistic can be computed directly on shared checkpoints without downloading any base model?",
        "Does an in-house Householder-ORBA reimplementation at 3-4B actually leave every singular value intact in bf16, or does the accumulated floating-point error the ORBA author warns about ('misdirected sign-flips') create a spurious near-null direction that makes the sharpest falsification test unreliable in the precision the panel actually uses?",
    ],
}

(WS / "research_out.json").write_text(json.dumps(out, indent=1))
print("wrote research_out.json;", len(json.dumps(out)), "bytes")
